language: objective-c
cache: cocoapods
rvm: 2.2.2
osx_image: xcode8

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Sourcery.xcworkspace
  - SCHEME=Sourcery

before_install:
#  - gem install cocoapods -v 1.1.0.rc2 # remove -v after it ships
  - gem install xcpretty

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build | xcpretty

  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test | xcpretty

#  - pod _1.1.0.rc2_ lib lint

after_success:
- bash <(curl -s https://codecov.io/bash)
